### ISSUE TITLE
Can't install with Rails 5.0.2

### ISSUE THREAD

**Issue by pjb3** [ankane/blazer#148]
I'm trying to add Blazer to a Rails 5.0.1 app and when I run blazer:install, I get this:

```
$ rails g blazer:install
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activerecord-5.0.2/lib/active_record/dynamic_matchers.rb:21:in `method_missing': undefined method `configurations' for ActiveRecord::Base:Class
Did you mean?  configurations= (NoMethodError)
	from /Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/application.rb:345:in `active_record_configured?'
	from /Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/application.rb:263:in `disconnect_database'
	from /Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/application.rb:97:in `preload'
	from /Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
	from /Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
	from /Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
	from /Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
	from /Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/paul/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/paul/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by ankane** [comment]
Hey @pjb3, I use Blazer with a number of Rails 5 apps, so I think it's something specific to your app. Also, from the backtrace, looks like you're on ActiveRecord 5.0.2 fwiw.

**Comment by pjb3** [comment]
@ankane Right, 5.0.2. I was able to create the config file and the migration myself to get past it, so its not a blocker for me.

**Comment by ankane** [comment]
Cleaning up issues
