### ISSUE TITLE
Undefined method `start_with?` from sprockets

### ISSUE THREAD

**Issue by S-Cardenas** [ankane/blazer#258]
Hey,

Having a problem getting Blazer to play nicely with my Rails App. It seems that `blazer` and `sprockets` are not functioning correctly to together. I suspect it is really `chartkick` that is not playing nicely with `sprockets`. Below is the full stack trace:

```
factsmachine-web |  FATAL 2019-09-13T22:08:40.642642  ActionView::Template::Error (undefined method `start_with?' for #<Proc:0x00007f365c5a4670>):
factsmachine-web | Error during failsafe response: undefined method `start_with?' for #<Proc:0x00007f365c5a4670>
factsmachine-web |   /usr/local/bundle/gems/sprockets-4.0.0.beta10/lib/sprockets/uri_utils.rb:78:in `valid_asset_uri?'
factsmachine-web |   /usr/local/bundle/gems/sprockets-4.0.0.beta10/lib/sprockets/resolve.rb:27:in `resolve'
factsmachine-web |   /usr/local/bundle/gems/sprockets-4.0.0.beta10/lib/sprockets/base.rb:79:in `find_asset'
factsmachine-web |   /usr/local/bundle/gems/sprockets-4.0.0.beta10/lib/sprockets/base.rb:88:in `find_all_linked_assets'
factsmachine-web |   /usr/local/bundle/gems/sprockets-4.0.0.beta10/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/promise.rb:563:in `block in realize'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
factsmachine-web |   /usr/local/bundle/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

As well as the versions of each gem:

```
// gemfile
ruby '2.5.3'
gem 'sprockets', '~> 4.0.0.beta8'
# ES6 sprockets
gem 'sprockets-es6', '~> 0.9', '>= 0.9.2'
gem 'blazer'
```

Any help would be useful as this doesn't seem to be occuring to anyone else.

Thanks.

```
//gemfile.lock
    blazer (2.2.0)
      activerecord (>= 5)
      chartkick (>= 3.2)
      railties (>= 5)
      safely_block (>= 0.1.1)
```

**Comment by ankane** [comment]
Hey @S-Cardenas, I haven't seen that error before, but it may be due to Sprockets 4 beta. I'd try moving to a stable release of Sprockets to see if that fixes it.

**Comment by S-Cardenas** [comment]
Thanks for the speedy response @ankane . It seems this was the issue.

Best wishes.

**Comment by ankane** [comment]
fyi, Sprockets 4 was just released and had the same issue. Just pushed Blazer 2.2.1 which fixes it.
