### ISSUE TITLE
uninitialized constant #{candidates.first}", candidates.first

### ISSUE THREAD

**Issue by crystalschang** [ankane/blazer#32]
I've recently upgraded to blazer 1.0.3; previously I was on version 0.0.7.

I first ran into an issue where I couldn't save any new queries because we don't have a User class... I fixed that with the following addition to `blazer.yml`:

```
user_clas: nil
```

Now, I can save new queries but I'm getting an error when I'm trying to view the default home page which lists all of the queries. Here's a snippet of the error message:
```
NameError in Blazer::Queries#home
Showing /Users/crystal/.rvm/gems/ruby-2.2.0/gems/blazer-1.0.3/app/views/blazer/queries/_index.html.erb where line #1 raised:

uninitialized constant Blazer::Query::nil
       end
          raise NameError.new("uninitialized constant #{candidates.first}", candidates.first)
        end
      end


Trace of template inclusion: /Users/crystal/.rvm/gems/ruby-2.2.0/gems/blazer-1.0.3/app/views/blazer/queries/home.html.erb

Rails.root: /Users/crystal/workspace/mvln/reporter2

Application Trace | Framework Trace | Full Trace
activerecord (4.2.4) lib/active_record/inheritance.rb:158:in `compute_type'
activerecord (4.2.4) lib/active_record/reflection.rb:271:in `compute_class'
activerecord (4.2.4) lib/active_record/reflection.rb:267:in `klass'
activerecord (4.2.4) lib/active_record/associations/association.rb:118:in `klass'
activerecord (4.2.4) lib/active_record/associations/preloader.rb:158:in `block in grouped_records'
activerecord (4.2.4) lib/active_record/associations/preloader.rb:154:in `each'
activerecord (4.2.4) lib/active_record/associations/preloader.rb:154:in `grouped_records'
activerecord (4.2.4) lib/active_record/associations/preloader.rb:143:in `preloaders_for_one'
activerecord (4.2.4) lib/active_record/associations/preloader.rb:115:in `preloaders_on'
activerecord (4.2.4) lib/active_record/associations/preloader.rb:103:in `block in preload'
activerecord (4.2.4) lib/active_record/associations/preloader.rb:102:in `each'
```

Any thoughts of what's going on here? I haven't worked with Ruby/Rails much so if there's some expectation on how to set up Users for the tool, I've missed it (I haven't seen any details about it in the README). Getting users set up is a secondary concern though... first we just want to get the homepage backup and running. Thanks!

**Comment by ankane** [comment]
Hey @crystalschang, in `config/blazer.yml`, use:

```yml
user_class:
# instead of
user_class: nil
```

If that alone doesn't solve it, point your Gemfile to the master branch.

```ruby
gem "blazer", github: "ankane/blazer"
```

And run:

```ruby
bundle update blazer
```

**Comment by crystalschang** [comment]
Great, that first fix did it for me. Thanks for the quick response!

**Comment by ankane** [comment]
Cool, glad it's working.
