### ISSUE TITLE
Bug in Asset Pipeline Preventing Blazer From Mounting On Heroku Rails Instance

### ISSUE THREAD

**Issue by catonmat** [ankane/blazer#344]
### Reproducing
* Blazer works perfectly in the dev env but once it is deployed to Heroku it will not load.

### Backtrace
```
Sprockets::Rails::Helper::AssetNotFound: The asset "blazer/favicon.png" is not present in the asset pipeline.

  from vendor/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:84:in `compute_asset_path'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/helpers/asset_url_helper.rb:200:in `asset_path'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/helpers/asset_url_helper.rb:375:in `image_path'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/helpers/asset_tag_helper.rb:222:in `favicon_link_tag'
  from vendor/bundle/ruby/2.6.0/gems/blazer-2.2.6/app/views/layouts/blazer/application.html.erb:7
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/template.rb:159:in `block in render'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/template.rb:354:in `instrument_render_template'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/template.rb:157:in `render'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/renderer/template_renderer.rb:16:in `render'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/renderer/renderer.rb:44:in `render_template'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/renderer/renderer.rb:25:in `render'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/rendering.rb:103:in `_render_template'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/streaming.rb:219:in `_render_template'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/rendering.rb:84:in `render_to_body'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/abstract_controller/rendering.rb:25:in `render'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/rendering.rb:36:in `render'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
  from vendor/ruby-2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/core_ext/benchmark.rb:14:in `ms'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  from vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.0/lib/active_record/railties/controller_runtime.rb:31:in `cleanup_view_runtime'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:45:in `render'
  from vendor/bundle/ruby/2.6.0/gems/remotipart-1.4.4/lib/remotipart/render_overrides.rb:23:in `render'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:194:in `process_action'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:132:in `run_callbacks'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:41:in `process_action'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/rescue.rb:22:in `process_action'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
  from vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.0/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:134:in `process'
  from vendor/bundle/ruby/2.6.0/gems/actionview-5.2.0/lib/action_view/rendering.rb:32:in `process'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal.rb:191:in `dispatch'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_controller/metal.rb:252:in `dispatch'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:34:in `serve'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:52:in `block in serve'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `each'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `serve'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:840:in `call'
  from vendor/bundle/ruby/2.6.0/gems/railties-5.2.0/lib/rails/engine.rb:524:in `call'
  from vendor/bundle/ruby/2.6.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `public_send'
  from vendor/bundle/ruby/2.6.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `method_missing'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/mapper.rb:48:in `serve'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:52:in `block in serve'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `each'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `serve'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:840:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-pjax-1.1.0/lib/rack/pjax.rb:12:in `call'
  from vendor/bundle/ruby/2.6.0/gems/remotipart-1.4.4/lib/remotipart/middleware.rb:32:in `call'
  from vendor/bundle/ruby/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
  from vendor/bundle/ruby/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
  from vendor/bundle/ruby/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
  from vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/cookies.rb:670:in `call'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:98:in `run_callbacks'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from vendor/bundle/ruby/2.6.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:38:in `call_app'
  from vendor/bundle/ruby/2.6.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `block in call'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `block in tagged'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28:in `tagged'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `tagged'
  from vendor/bundle/ruby/2.6.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `call'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:151:in `block in call'
  from vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.6.0/lib/rack/timeout/support/timeout.rb:19:in `timeout'
  from vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:150:in `call'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:151:in `block in call'
  from vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.6.0/lib/rack/timeout/support/timeout.rb:19:in `timeout'
  from vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:150:in `call'
  from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
  from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/static.rb:127:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
  from vendor/bundle/ruby/2.6.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
  from vendor/bundle/ruby/2.6.0/gems/sentry-raven-3.1.2/lib/raven/integrations/rack.rb:51:in `call'
  from vendor/bundle/ruby/2.6.0/gems/railties-5.2.0/lib/rails/engine.rb:524:in `call'
  from vendor/bundle/ruby/2.6.0/gems/puma-5.3.2/lib/puma/configuration.rb:249:in `call'
  from vendor/bundle/ruby/2.6.0/gems/puma-5.3.2/lib/puma/request.rb:77:in `block in handle_request'
  from vendor/bundle/ruby/2.6.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:338:in `with_force_shutdown'
  from vendor/bundle/ruby/2.6.0/gems/puma-5.3.2/lib/puma/request.rb:76:in `handle_request'
  from vendor/bundle/ruby/2.6.0/gems/puma-5.3.2/lib/puma/server.rb:438:in `process_client'
  from vendor/bundle/ruby/2.6.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

**Comment by catonmat** [comment]
It was an issue with the Heroku assets pipeline and config file in our own source code. Not at all related to this package.
