### ISSUE TITLE
<Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)>

### ISSUE THREAD

**Issue by lentrup** [ankane/blazer#367]
First of all, thank you for making amazing open source software! 🙏 

I am getting this error:
`<Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)>
`
when trying to run any SQL query 

I am using:

- ruby 2.7.4
- `gem 'rails', '~> 6.1', '>= 6.1.4.1'`
- `gem "blazer", github: "ankane/blazer"`
- also tried `gem 'blazer', '~> 2.4', '>= 2.4.7'` , same error

<details>

<summary>Backtrace</summary>

```
[Tracing] Starting <rails.request> transaction </blazer/queries/run>
Started POST "/blazer/queries/run" for 127.0.0.1 at 2021-11-09 21:03:31 +0100
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
Processing by Blazer::QueriesController#run as HTML
  Parameters: {"statement"=>"", "data_source"=>"main", "run_id"=>"82d4d7ca-1eeb-4a33-8345-b902ed08997a"}
  TRANSACTION (0.2ms)  BEGIN
  Blazer::Audit Create (1.4ms)  INSERT INTO "blazer_audits" ("user_id", "statement", "data_source", "created_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["user_id", 2], ["statement", ""], ["data_source", "main"], ["created_at", "2021-11-09 20:03:31.168343"]]
  TRANSACTION (2.6ms)  COMMIT
  TRANSACTION (0.2ms)  BEGIN
   (0.1ms)   /*blazer,user_id:2,run_id:82d4d7ca-1eeb-4a33-8345-b902ed08997a*/
  TRANSACTION (0.2ms)  ROLLBACK
  Rendering /Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/bundler/gems/blazer-0e22613b5468/app/views/blazer/queries/run.html.erb
  Rendered /Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/bundler/gems/blazer-0e22613b5468/app/views/blazer/queries/_caching.html.erb (Duration: 0.9ms | Allocations: 262)
  Rendered /Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/bundler/gems/blazer-0e22613b5468/app/views/blazer/queries/run.html.erb (Duration: 8.2ms | Allocations: 3510)
Completed 200 OK in 37ms (Views: 11.0ms | ActiveRecord: 8.9ms | Allocations: 15512)


2021-11-09 21:03:31 +0100: Rack app error handling request { POST /queries/run }
#<Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)>
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/helpers/javascript_helper.rb:34:in `gsub'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/helpers/javascript_helper.rb:34:in `escape_javascript'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/turbolinks_render-0.9.21/lib/turbolinks_render/middleware.rb:46:in `js_code_to_render_html'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/turbolinks_render-0.9.21/lib/turbolinks_render/middleware.rb:23:in `turbolinks_body'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/turbolinks_render-0.9.21/lib/turbolinks_render/middleware.rb:87:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/rack/logger.rb:37:in `call_app'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/rack/logger.rb:26:in `block in call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/tagged_logging.rb:37:in `tagged'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/tagged_logging.rb:99:in `tagged'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/rack/logger.rb:26:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sentry-ruby-core-4.7.3/lib/sentry/rack/capture_exceptions.rb:23:in `block in call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sentry-ruby-core-4.7.3/lib/sentry/hub.rb:56:in `with_scope'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sentry-ruby-core-4.7.3/lib/sentry-ruby.rb:176:in `with_scope'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/sentry-ruby-core-4.7.3/lib/sentry/rack/capture_exceptions.rb:14:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/static.rb:24:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/actionpack-6.1.4.1/lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/webpacker-5.4.3/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rack-proxy-0.7.0/lib/rack/proxy.rb:63:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/engine.rb:539:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puma-4.3.8/lib/puma/configuration.rb:228:in `call'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puma-4.3.8/lib/puma/server.rb:718:in `handle_request'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puma-4.3.8/lib/puma/server.rb:472:in `process_client'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puma-4.3.8/lib/puma/server.rb:328:in `block in run'
/Users/leon/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/puma-4.3.8/lib/puma/thread_pool.rb:134:in `block in spawn_thread'


```

</details>

**Comment by ankane** [comment]
Hey @lentrup, from the stack trace, it looks like it may be caused by `turbolinks_render`. I'd try removing it to see if that fixes it.

**Comment by lentrup** [comment]
that did it. thank you for the quick reply.
