### ISSUE TITLE
ArgumentError `blazer/data_source.rb` in sort_by comparison of String with Integer failed after upgrading to 2.6.3 from 2.4.2

### ISSUE THREAD

**Issue by lemeo** [ankane/blazer#401]
Hey @ankane,

Thanks so much for helping with the `Unknown data source:` issue(https://github.com/ankane/blazer/issues/398) while upgrading to version 2.6.3 and that fix has been working great. But, now we are seeing a new issue.
We have a blazer query that takes tech_id as a variable (please see the attached screenshot). It works great
with version 2.4.2 but it breaks with the version 2.6.3 with the following error message:
```
ArgumentError blazer/data_source.rb in sort_by
comparison of String with 218328 failed
```

Following is the complete stack trace:
```
ArgumentError: comparison of String with 218328 failed
  from blazer/data_source.rb:148:in `sort_by'
  from blazer/data_source.rb:148:in `statement_cache_key'
  from blazer/data_source.rb:111:in `run_statement'
  from blazer/run_statement.rb:21:in `perform'
  from blazer/run_statement_job.rb:11:in `block in perform'
  from active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
  from blazer/run_statement_job.rb:10:in `perform'
  from active_job/execution.rb:48:in `block in perform_now'
  from active_support/callbacks.rb:117:in `block in run_callbacks'
  from raven/integrations/rails/active_job.rb:18:in `capture_and_reraise_with_sentry'
  from raven/integrations/rails/active_job.rb:12:in `block (2 levels) in included'
  from active_support/callbacks.rb:126:in `instance_exec'
  from active_support/callbacks.rb:126:in `block in run_callbacks'
  from i18n.rb:328:in `with_locale'
  from active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
  from active_support/callbacks.rb:126:in `instance_exec'
  from active_support/callbacks.rb:126:in `block in run_callbacks'
  from active_support/core_ext/time/zones.rb:66:in `use_zone'
  from active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
  from active_support/callbacks.rb:126:in `instance_exec'
  from active_support/callbacks.rb:126:in `block in run_callbacks'
  from active_job/instrumentation.rb:21:in `block in instrument'
  from active_support/notifications.rb:203:in `block in instrument'
  from active_support/notifications/instrumenter.rb:24:in `instrument'
  from active_support/notifications.rb:203:in `instrument'
  from active_job/instrumentation.rb:31:in `instrument'
  from active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
  from active_support/callbacks.rb:126:in `instance_exec'
  from active_support/callbacks.rb:126:in `block in run_callbacks'
  from active_job/logging.rb:22:in `block in tag_logger'
  from active_support/tagged_logging.rb:99:in `block in tagged'
  from active_support/tagged_logging.rb:37:in `tagged'
  from active_support/tagged_logging.rb:99:in `tagged'
  from active_job/logging.rb:22:in `tag_logger'
  from active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
  from active_support/callbacks.rb:126:in `instance_exec'
  from active_support/callbacks.rb:126:in `block in run_callbacks'
  from active_support/callbacks.rb:137:in `run_callbacks'
  from active_job/execution.rb:47:in `perform_now'
  from active_job/execution.rb:25:in `block in execute'
  from active_support/callbacks.rb:117:in `block in run_callbacks'
  from active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
  from active_support/execution_wrapper.rb:91:in `wrap'
  from active_support/reloader.rb:72:in `block in wrap'
  from active_support/execution_wrapper.rb:91:in `wrap'
  from active_support/reloader.rb:71:in `wrap'
  from active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
  from active_support/callbacks.rb:126:in `instance_exec'
  from active_support/callbacks.rb:126:in `block in run_callbacks'
  from active_support/callbacks.rb:137:in `run_callbacks'
  from active_job/execution.rb:23:in `execute'
  from active_job/queue_adapters/async_adapter.rb:70:in `perform'
  from concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
  from concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
  from concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
  from concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
  from concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
  from concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
  ```
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/5613492/170166865-757e1419-eb8e-4b60-9cf9-0ff22bbb346b.png">

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/5613492/170166909-03c93f2f-1459-4cce-b9f9-63d2824f52e5.png">

Could you please let us know how to make a variable like this work with the latest version of blazer gem? Thank you.

**Comment by ankane** [comment]
Thanks for another great report! Will push a new release later tonight.
