### ISSUE TITLE
Variables don't work with Rails <= v5.2.0

### ISSUE THREAD

**Issue by bnlucas** [ankane/blazer#411]
This isn't an issue with Blazer, but wanted to point out the changes made in v2.6.0 for https://github.com/ankane/blazer/issues/392 have caused variables to no longer work in Rails <= 5.2.0.

While trying to update to v2.6.4 due to the SQL injection vulnerability, it was noticed that all of our saved queries containing variables stopped working, giving the following:

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/1596170/187555164-64136f2f-5476-4693-8b68-0c53c2ecaae9.png">

After investigating the cause of this, I stumbled upon https://github.com/rails/rails/pull/31320. The fix for this is in Rails >= 5.2.1.

I noticed there's testing on both ~> 5.0.0 and ~> 5.1.0 in the build workflow, but not at the controller level so this has gone unnoticed.

If anyone else is encountering this issue, know that you can update to v2.5.0 but you don't get the fix for the SQL injection.

**Comment by ankane** [comment]
Hey @bnlucas, thanks for the report. However, I'm not sure how to reproduce (that view [is tested](https://github.com/ankane/blazer/blob/v2.6.4/test/queries_test.rb#L81-L82) and there's [specific code](https://github.com/ankane/blazer/blob/v2.6.4/app/views/blazer/queries/show.html.erb#L7) for Rails 5.0). Can you paste the complete stack trace?

**Comment by bnlucas** [comment]
When testing the upgrade, I used this query:

```sql
select * from users where created_at >= {created_at}
```

Here's the full trace:

```text
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/helpers/url_helper.rb:648:in `sort_by'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/helpers/url_helper.rb:648:in `to_form_params'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/helpers/url_helper.rb:332:in `button_to'
/usr/local/bundle/gems/blazer-2.6.4/app/views/blazer/queries/show.html.erb:24:in `__usr_local_bundle_gems_blazer_______app_views_blazer_queries_show_html_erb__3788271108161901590_231660'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/template.rb:157:in `block in render'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/template.rb:352:in `instrument_render_template'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/template.rb:155:in `render'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:166:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/renderer/template_renderer.rb:14:in `render'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/renderer/renderer.rb:42:in `render_template'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/renderer/renderer.rb:23:in `render'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/rendering.rb:103:in `_render_template'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/rendering.rb:83:in `render_to_body'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/abstract_controller/rendering.rb:24:in `render'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/rendering.rb:36:in `render'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/usr/local/bundle/gems/activerecord-5.1.6.2/lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/instrumentation.rb:43:in `render'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/implicit_render.rb:33:in `default_render'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/abstract_controller/base.rb:186:in `process_action'
/usr/local/bundle/gems/ddtrace-1.0.0/lib/datadog/tracing/contrib/action_pack/action_controller/instrumentation.rb:125:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:166:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/usr/local/bundle/gems/activerecord-5.1.6.2/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/abstract_controller/base.rb:124:in `process'
/usr/local/bundle/gems/actionview-5.1.6.2/lib/action_view/rendering.rb:30:in `process'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal.rb:189:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_controller/metal.rb:253:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:33:in `each'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:33:in `serve'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/route_set.rb:844:in `call'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/engine.rb:522:in `call'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/railtie.rb:185:in `public_send'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/railtie.rb:185:in `method_missing'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/mapper.rb:46:in `serve'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:33:in `each'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/journey/router.rb:33:in `serve'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/routing/route_set.rb:844:in `call'
/usr/local/bundle/gems/turnout-2.4.1/lib/rack/turnout.rb:25:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/cypress-on-rails-1.12.1/lib/cypress_on_rails/middleware.rb:20:in `call'
/usr/local/bundle/gems/bullet-5.9.0/lib/bullet/rack.rb:15:in `call'
/usr/local/bundle/gems/apollo_upload_server-2.0.0.alpha.5/lib/apollo_upload_server/middleware.rb:20:in `call'
/usr/local/bundle/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
/usr/local/bundle/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
/usr/local/bundle/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
/usr/local/bundle/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.4/lib/rack/conditional_get.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/bundle/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/usr/local/bundle/gems/activerecord-5.1.6.2/lib/active_record/migration.rb:556:in `call'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/callbacks.rb:97:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
/usr/local/bundle/gems/ddtrace-1.0.0/lib/datadog/tracing/contrib/rails/middlewares.rb:20:in `call'
/usr/local/bundle/gems/rollbar-3.3.0/lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
/usr/local/bundle/gems/rollbar-3.3.0/lib/rollbar.rb:145:in `scoped'
/usr/local/bundle/gems/rollbar-3.3.0/lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
/usr/local/bundle/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:59:in `call'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/usr/local/bundle/gems/rollbar-3.3.0/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/usr/local/bundle/gems/kali-client-0.0.49/lib/kali/client/callback_middleware.rb:22:in `call'
/usr/local/bundle/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/rack/logger.rb:24:in `block in call'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/tagged_logging.rb:69:in `tagged'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/rack/logger.rb:24:in `call'
/usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/usr/local/bundle/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/usr/local/bundle/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
/usr/local/bundle/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
/usr/local/bundle/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/static.rb:125:in `call'
/usr/local/bundle/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
/usr/local/bundle/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/usr/local/bundle/gems/ddtrace-1.0.0/lib/datadog/tracing/contrib/rack/middlewares.rb:84:in `call'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/engine.rb:522:in `call'
/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:634:in `process_client'
/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:739:in `worker_loop'
/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:547:in `spawn_missing_workers'
/usr/local/bundle/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:143:in `start'
/usr/local/bundle/gems/unicorn-rails-2.2.1/lib/unicorn_rails.rb:33:in `run'
/usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:327:in `start'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:44:in `start'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:135:in `block in perform'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:130:in `tap'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/commands/server/server_command.rb:130:in `perform'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/command/base.rb:63:in `perform'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/command.rb:44:in `invoke'
/usr/local/bundle/gems/railties-5.1.6.2/lib/rails/commands.rb:16:in `<main>'
/usr/local/bundle/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/deploy/app/config/boot.rb:10:in `block in require'
/usr/local/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/home/deploy/app/config/boot.rb:9:in `require'
bin/rails:8:in `<main>'
```

**Comment by ankane** [comment]
Thanks @bnlucas. Was able to reproduce with that Rails version. It looks like the `button_to` fix [was backported](https://github.com/rails/rails/blob/v5.1.7/actionview/CHANGELOG.md#rails-517-march-27-2019) to Rails 5.1.7, which is why the tests weren't catching it. Just pushed a fix.

**Comment by bnlucas** [comment]
Amazing, thank you!
