### ISSUE TITLE
Is this project not Rails 7 compatible?

### ISSUE THREAD

**Issue by jasonperrone** [ankane/blazer#418]
Upgraded to Ruby 3.1.2, Rails 7.0.4. On application startup, I get this:

```
NameError: uninitialized constant Blazer::BaseController
   class QueriesController < BaseController
                             ^^^^^^^^^^^^^^
/webapps/myapp/staging/shared/bundle/ruby/3.1.0/gems/blazer-2.6.5/app/controllers/blazer/queries_controller.rb:2:in `<module:Blazer>'
 /webapps/myappr/staging/shared/bundle/ruby/3.1.0/gems/blazer-2.6.5/app/controllers/blazer/queries_controller.rb:1:in `<top (required)>'
 /webapps/myapp/staging/releases/20220929132837/config/initializers/blazer_utf8.rb:2:in `load'
 /webapps/myapp/staging/releases/20220929132837/config/initializers/blazer_utf8.rb:2:in `<top (required)>'
```

I mean, this project seems active and well maintained, I am surprised no one else has tried running this on this tech stack, or am I doing something wrong? This seems like this project does not work with zeitwerk, which is the only class loader available in Rails 7.

**Comment by jasonperrone** [comment]
I think this is my app's fault. We have an initializer to prepend a method to the QueriesController. Sorry.
