### ISSUE TITLE
Everything is ok in development mode , But I got error on Production

### ISSUE THREAD

**Issue by amirreza-one** [ankane/blazer#60]
I use nginx on my server, When I add blazer into my gemfile and execute 'bundle' command and then restart my 'nginx' Server , I got error in my passenger log file and my website doesn't work anymore

my nginx error log file is:

```
[ 2016-05-08 12:18:21.3869 6103/7ff65c471700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/deploy/www/tagisland: An e$
  Error ID: 2dbc4b07
  Error details saved to: /tmp/passenger-error-vf2NHV.html
  Message from application: Unknown key: :required. Valid keys are: :class_name, :class, :foreign_key, :validate, :autosave, :remote, :dependent, :primary_$
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/core_ext/hash/keys.rb:71:in `block in assert_valid_key$
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/core_ext/hash/keys.rb:69:in `each_key'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/core_ext/hash/keys.rb:69:in `assert_valid_keys'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.1.2/lib/active_record/associations/builder/association.rb:81:in `validate_opti$
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.1.2/lib/active_record/associations/builder/association.rb:61:in `initialize'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.1.2/lib/active_record/associations/builder/association.rb:46:in `new'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.1.2/lib/active_record/associations/builder/association.rb:46:in `create_builde$
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.1.2/lib/active_record/associations/builder/association.rb:35:in `build'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.1.2/lib/active_record/associations.rb:1433:in `belongs_to'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/blazer-1.3.2/app/models/blazer/audit.rb:3:in `<class:Audit>'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/blazer-1.3.2/app/models/blazer/audit.rb:2:in `<module:Blazer>'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/blazer-1.3.2/app/models/blazer/audit.rb:1:in `<top (required)>'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `block in require'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:348:in `require_or_load'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:307:in `depend_on'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:225:in `require_dependency'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:467:in `each'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:467:in `block in eager_load!'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:465:in `each'
/home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:465:in `each'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:465:in `eager_load!'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/engine.rb:346:in `eager_load!'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/application/finisher.rb:58:in `each'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/initializable.rb:30:in `instance_exec'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/initializable.rb:30:in `run'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/initializable.rb:55:in `block in run_initializers'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/initializable.rb:54:in `run_initializers'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-4.1.2/lib/rails/application.rb:300:in `initialize!'
  /home/deploy/www/tagisland/config/environment.rb:7:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
  /home/deploy/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

```

PLEASE HELP ME

**Comment by ankane** [comment]
Thanks for reporting @amirreza-one! This is fixed in the latest version.
