### ISSUE TITLE
Attempting to generate a URL from non-sanitized request parameters! 

### ISSUE THREAD

**Issue by mimmo** [ankane/blazer#70]
If i add smart variables to blazer configuration i get this error.
This is the partial stack trace of the error
```
Blazer::Query Load (0.3ms)  SELECT  "blazer_queries".* FROM "blazer_queries" WHERE "blazer_queries"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (0.2ms)  BEGIN
   (0.2ms)  SELECT id, title FROM posts ORDER BY title ASC /*blazer*/
   (0.2ms)  ROLLBACK
  Rendering vendor/bundle/gems/blazer-1.4.0/app/views/blazer/queries/show.html.erb within layouts/blazer/application
  Rendered vendor/bundle/gems/blazer-1.4.0/app/views/blazer/_nav.html.erb (1.1ms)
  Rendered vendor/bundle/gems/blazer-1.4.0/app/views/blazer/queries/show.html.erb within layouts/blazer/application (11.4ms)
Completed 500 Internal Server Error in 23ms (ActiveRecord: 0.8ms)

ArgumentError - Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.:
  actionpack (5.0.0.beta4) lib/action_dispatch/routing/url_for.rb:176:in `url_for'
  actionview (5.0.0.beta4) lib/action_view/routing_url_for.rb:96:in `url_for'
  blazer (1.4.0) app/views/blazer/queries/show.html.erb:55:in `_vendor_bundle_gems_blazer_______app_views_blazer_queries_show_html_erb___1963724263189473542_70206828597120'
...
```
Could you help me?

**Comment by mimmo** [comment]
It seems to be related to rails 5 beta1 release. 
https://github.com/rails/rails/commit/4752e7d83794ecf23c6d0367f0bcad8eee33da59

**Comment by ankane** [comment]
Thanks for reporting @mimmo! Will push a release later tonight (or you can start using master immediately).
