### ISSUE TITLE
Error on new Query: ActionView::Template::Error (Empty url)

### ISSUE THREAD

**Issue by jalberto** [ankane/blazer#89]
I am trying ot use blazer in prod, but I have this error as when trying to create a new query:

```
Started GET "/admin/reports/queries/new" for 192.168.99.1 at 2016-10-14 16:48:28 +0000
Processing by Blazer::QueriesController#new as HTML
  Rendering /usr/local/bundle/gems/blazer-1.7.0views/layouts/blazer/application.html.erb
  Rendering /usr/local/bundle/gems/blazer-1.7.0views/blazer/queries/new.html.erb within layouts/blazer/application
  Rendered /usr/local/bundle/gems/blazer-1.7.0views/blazer/queries/_form.html.erb (12.5ms)
  Rendered /usr/local/bundle/gems/blazer-1.7.0views/blazer/queries/new.html.erb within layouts/blazer/application (13.2ms)
  Rendered /usr/local/bundle/gems/blazer-1.7.0views/layouts/blazer/application.html.erb (13.6ms)
Completed 500 Internal Server Error in 16ms (ActiveRecord: 0.0ms)
  
ActionView::Template::Error (Empty url):
    15:         <div class="pull-left" style="margin-top: 6px;">
    16:           <%= link_to "Back", :back %>
    17:         </div>
    18:         <%= f.select :data_source, Blazer.data_sources.values.map { |ds| [ds.name, ds.id] }, {}, class: ("hide" if Blazer.data_sources.size == 1), style: "width: 140px;" %>
    19:         <div id="tables" style="display: inline-block; width: 250px; margin-right: 10px;" class="hide">
    20:           <%= render partial: "tables" %>
    21:         </div>
  
blazer (1.7.0) lib/blazer/data_source.rb:16:in `initialize'
blazer (1.7.0) lib/blazer.rb:73:in `new'
blazer (1.7.0) lib/blazer.rb:73:in `block in data_sources'
```
Creating dashboards works, so DB access seems right, looks liek the link_to is failling somehow

**Comment by jalberto** [comment]
My fault, by the error message I thought the problem was different, I suggest to change the error message to somethign like "Database URL not present"

**Comment by ankane** [comment]
@jalberto Updated the error message.

**Comment by andreydeineko** [comment]
I am getting the exact same error and not sure what should I do. I as well can create Dashboard. Moreover, locally everything works smoothly, only on production the error occurs only for `New query`...
